version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: ims-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
